version: "3.3"
services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  server:
    build: .
    depends_on:
      - mqtt
    env_file: ./.env
    environment:
      - MQTT_URL=mqtt://mqtt
    ports:
      - 8001:8001
    volumes:
      - ./.data:/opt/record-player-server/.data
